### ISSUE TITLE
[FEAT]: Organisation Invitation System - Backend

### ISSUE THREAD

**Issue by willgee9531** [willgee9531/organisations#1]
## Description
Create a backend system for inviting users to organisations via email and shareable links.

## Acceptance Criteria

- Admins can create invitations with a unique token and expiration date
- Users receive invitation emails with a secure link
- Users can accept invitations and join organisations
- Invitations expire after a set period of time
- Admins can manage (list, revoke, resend) invitations

## Expected Outcome
- A fully functional invitation system that allows organisation admins to invite new members, and users to join organisations through secure, time-limited invitations.

### 1. Create Invitation [POST] /api/organisations/{orgId}/invitations

**Request Body:**
```json
{
  "email": "user@example.com",
  "role": "member"
}
```
**Success Response (201 Created):**
```json
{
  "message": "Invitation sent successfully",
  "invitation": {
    "id": "inv_123",
    "email": "johndoe@example.com",
    "role": "member",
    "expiresAt": "2023-07-23T00:00:00Z"
  }
}
```
**Failure Response (400 Bad Request):**
```json
{
  "error": "Invalid request",
  "message": "Email already has a pending invitation"
}
```

### 2. Accept Invitation [POST] /api/invitations/accept

**Request Body:**
```json
{
  "token": "abcdef123456"
}
```
**Success Response (200 OK):**
```json
{
  "message": "Invitation accepted successfully",
  "organisation": {
    "id": "org_123",
    "name": "My Organisation"
  }
}
```
**Failure Response (400 Bad Request):**
```json
{
  "error": "Invalid invitation",
  "message": "The invitation token is invalid or has expired"
}
```

### 3. List Invitations [GET] /api/organisations/{orgId}/invitations

**Success Response (200 OK):**
```json
{
  "invitations": [
    {
      "id": "inv_123",
      "email": "user1@example.com",
      "role": "member",
      "expiresAt": "2023-07-23T00:00:00Z"
    },
    {
      "id": "inv_124",
      "email": "user2@example.com",
      "role": "admin",
      "expiresAt": "2023-07-24T00:00:00Z"
    }
  ]
}
```
**Failure Response (403 Forbidden):**
```json
{
  "error": "Access denied",
  "message": "You don't have permission to view invitations for this organisation"
}
```

### 4. Revoke Invitation [DELETE] /api/organisations/{orgId}/invitations/{invitationId}

**Success Response (204 No Content)**

**Failure Response (404 Not Found):**
```json
{
  "error": "Not found",
  "message": "Invitation not found or already processed"
}
```

### 5. Resend Invitation [POST] /api/organisations/{orgId}/invitations/{invitationId}/resend

**Success Response (200 OK):**
```json
{
  "message": "Invitation resent successfully",
  "invitation": {
    "id": "inv_123",
    "email": "user@example.com",
    "expiresAt": "2023-07-30T00:00:00Z"
  }
}
```
**Failure Response (400 Bad Request):**
```json
{
  "error": "Invalid request",
  "message": "Invitation has already been accepted or expired"
}
```

## Database Design

```dbml
Table invitations {
  id integer [primary key]
  organisation_id integer [ref: > organisations.id]
  email varchar
  role varchar
  token varchar [unique]
  created_at timestamp
  expires_at timestamp
  accepted_at timestamp
}

Indexes {
  (invitations.token) [name: 'idx_invitations_token']
  (invitations.email) [name: 'idx_invitations_email']
}
```

## Tasks

- [ ] Design database schema for invitations
- [ ] Create API for generating invitations
- [ ] Implement email sending for invitations
- [ ] Create API for accepting invitations
- [ ] Develop API for managing invitations (list, revoke, resend)
- [ ] Implement invitation expiration logic
- [ ] Write tests for the invitation system

## Testing

- Unit tests for invitation creation and acceptance logic
- Integration tests for the end-to-end invitation flow
- Security tests for token generation and validation

---
